apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: guestbook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: guestbook-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: guestbook-app
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v1
        ports:
          - containerPort: 6379
